### ISSUE TITLE
Query: local testing

### ISSUE THREAD

**Issue by chenhendrawan** [bennylope/screenshooter#6]
Hi,
Does the screenshooter works with browserstack local testing https://www.browserstack.com/local-testing?
I tried running the Browserstack local testing binary, then running the screenshooter script, but doesn't seem to work to screenshot our internal servers. Just wondering if this use case is not supported or something wrong in my setup.
Thanks,
Chen

**Comment by bennylope** [comment]
I think it could be, but screenshooter just needs to be updated to specify local testing to the [screenshots dependency](https://github.com/browserstack/ruby-screenshots/blob/88ce2b35eb2b4caa03bd847098386d91de8305da/README.md#for-testing-localinternal-server-setup). As-is it probably won't work.

**Comment by chenhendrawan** [comment]
Wow what a quick response :). 
I have a look at screenshooter.rb, and the API parameters were read from the browser.yaml file. So I modified the my browser.yaml file to add the tunnel parameter. However this is still not working.

Anyway, probably this question is more suitable for the Browserstack guys, but I really appreciate any help from you.

**Comment by akhillb** [comment]
I added the parameter "local" and set it to true in the browsers.yaml file and it worked fine for me. Try running the binary with -forcelocal option and check.
