### ISSUE TITLE
Add option to completely silence screenshooter.

### ISSUE THREAD

**Issue by lemzwerg** [bennylope/screenshooter#9]
Currently, option `--wait` makes screenshooter chatty.  This is not ideal for Makefiles that are executed as `make -j`, where multiple calls to the screenshooter are processed in parallel.

So please add an option `-q`/`--quiet` to suppress any informational output.

**Comment by bennylope** [comment]
Quieter than [this](https://github.com/bennylope/screenshooter/commit/24e33d496358e5763c71ba29e43cc3c013451573)?

**Comment by lemzwerg** [comment]
This is just fine, thanks!
